spring:
  datasource:
    druid:
      url:  jdbc:mysql:/localhost:3306/gulimall_ums?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: a1300295338
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
#      server-addr: localhost:8848
      discovery:
        namespace: 5d72b4fb-f8cf-47f2-9025-c6a85dc5d043
        cluster-name: nz

  application:
    name: gulimall-member
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8092
